version: "3"
services:
  db:
    image: postgres:15.1-alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=vxtell
      - POSTGRES_PASSWORD=vxtell123
      - POSTGRES_DB=vxtell
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data